name: base

channels:
 - conda-forge

dependencies:
  - pandas
  - xlrd
  - numpy
  - matplotlib
  - statsmodels
  - scikit-learn
  - imbalanced-learn
  - bokeh
  - notebook
  - jupyter
  - jupyter_contrib_nbextensions
  - jupyterlab
